version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/inti.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    command: >
      bash -c "until nc -z -v -w30 zookeeper 2181; do echo 'Waiting for Zookeeper...'; sleep 5; done; 
      /etc/confluent/docker/run"
  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  product:
    build: './product-service'
    container_name: product
    ports:
      - "8080:8090"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATA_MONGODB_URI: 'mongodb://root:password@mongodb:27017/product-service?authSource=admin'
  order:
    build: './order-service'
    container_name: order
    ports:
      - "8081:8091"
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/order_service'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'mysql'
  cart:
    build: './cart-service'
    container_name: cart
    ports:
      - "8082:8092"
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/cart_service'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'mysql'
  payment:
    build: './payment-service'
    container_name: payment
    ports:
      - "8083:8093"
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/payment_service'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'mysql'
  inventory:
    build: './inventory-service'
    container_name: inventory
    ports:
      - "8084:8094"
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/inventory_service'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'mysql'
  user:
    build: './user-service'
    container_name: user
    ports:
      - "8085:8095"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      SPRING_DATA_MONGODB_URI: 'mongodb://root:password@mongodb:27017/user-service?authSource=admin'
  search:
    build: './search-service'
    container_name: search
    ports:
      - "8086:8096"
    depends_on:
      - kafka
    environment:
      DEVTIRO_KAFKA_TOPIC: 'product'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
  notification:
    build: './notification-service'
    container_name: notification
    ports:
      - "8087:8097"
    depends_on:
      - kafka
    environment:
      DEVTIRO_KAFKA_TOPICS: 'order-placed, order-delivered, order-cancelled, payment-completed, refund-initiated, refund-completed, review-added, profile-completed, profile-updated'
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'