version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: payment-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: payment_service
    ports:
      - "3326:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/inti.sql:/docker-entrypoint-initdb.d/init.sql